name: vola
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auth_client:
    path: packages/auth_client
  cupertino_icons: ^1.0.2
  db_client:
    path: packages/db_client
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  file_upload_client:
    path: packages/file_upload_client
  intl: any
  models:
    path: packages/models
  envied: ^0.5.2
  flutter_launcher_icons: ^0.13.1
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter_svg: ^2.0.10+1
  logging: ^1.2.0
  firebase_storage: ^11.7.6
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  envied_generator: ^0.5.2
  build_runner: ^2.4.7

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    # - assets/videos/
    #- assets/audios/
