name: data_loader
description: "A simple Flutter app to load the sample data into your database"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  models:
    path: ../models
  db_client:
    path: ../db_client
  firebase_core: ^2.24.2
  firebase_storage: ^11.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
