// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRId9OchURSl1v_kmIrm4mdsJpI1ar020',
    appId: '1:901584396201:web:5deb068b86d9901833eeb8',
    messagingSenderId: '901584396201',
    projectId: 'vola-976e5',
    authDomain: 'vola-976e5.firebaseapp.com',
    storageBucket: 'vola-976e5.appspot.com',
    measurementId: 'G-4K90XWTNEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0FAfTc7A3y8dqg7yzHMXr0YJX0jBp9ZM',
    appId: '1:901584396201:android:24e370fcd898a46733eeb8',
    messagingSenderId: '901584396201',
    projectId: 'vola-976e5',
    storageBucket: 'vola-976e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOUR3V_BgB9H_xCW6XSV8bxv73ESebwJs',
    appId: '1:901584396201:ios:cdc1f4dce59fc5f333eeb8',
    messagingSenderId: '901584396201',
    projectId: 'vola-976e5',
    storageBucket: 'vola-976e5.appspot.com',
    iosBundleId: 'com.example.vola',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOUR3V_BgB9H_xCW6XSV8bxv73ESebwJs',
    appId: '1:901584396201:ios:cdc1f4dce59fc5f333eeb8',
    messagingSenderId: '901584396201',
    projectId: 'vola-976e5',
    storageBucket: 'vola-976e5.appspot.com',
    iosBundleId: 'com.example.vola',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRId9OchURSl1v_kmIrm4mdsJpI1ar020',
    appId: '1:901584396201:web:c60cf1502c5f907c33eeb8',
    messagingSenderId: '901584396201',
    projectId: 'vola-976e5',
    authDomain: 'vola-976e5.firebaseapp.com',
    storageBucket: 'vola-976e5.appspot.com',
    measurementId: 'G-DQK4BMS63F',
  );
}
